name: Lint
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Check for Flake8 config
      run: |
        FLAKE8=.flake8
        if [ -e ./"$FLAKE8" ]; then
            echo "A .flake8 config file has been found in the root of this branch and will be used in this workflow."
        else
            echo "No .flake8 config file has been found in the root of this branch and so the standard Data Engineering config will used."
            curl https://moj-analytical-services.github.io/.github/configs/data-engineering/flake8 > .flake8
        fi
    - name: Check for YAMLLINT config
      run: |
        YAMLLINT=.yamllint
        if [ -e ./"$YAMLLINT" ]; then
            echo "A .yamllint config file has been found in the root of this branch and will be used in this workflow."
        else
            echo "No .yamllint config file has been found in the root of this branch and so the standard Data Engineering config will used."
            curl https://moj-analytical-services.github.io/.github/configs/data-engineering/yamllint > .yamllint
        fi

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint Python files with flake8
      run: >
        flake8 .
    - name: Lint YAML files with yamllint
      run: >
        yamllint .
